##port
server:
  port: 7777

# H2 Setting
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  messages:
    basename: i18n/exception
    encoding: UTF-8
  redis:
    host: localhost
    port: 6379

#mybatis 설정
mybatis:  mapper-locations: mappers/**/*.xml  configuration:    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: false

